version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    commit-message:
      prefix: "🤖 "
    groups:
      typescript-eslint:
        patterns:
          - "@typescript-eslint*"
      eslint:
        patterns:
          - "eslint*"
