version: 2.1
jobs:
  build:
    working_directory: ~/slow-zone
    docker:
      - image: cimg/node
    environment:
      TZ: "America/Chicago"
    steps:
      - checkout
      - restore_cache:
          key: npm-cache-{{ checksum "package.json" }}
      - run:
          name: install
          command: npm ci
      - save_cache:
          key: npm-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: test
          command: npm test
