version: 2
jobs:
  build:
    working_directory: ~/slow-zone
    docker:
      - image: circleci/node:lts
    environment:
      TZ: "America/Chicago"
    steps:
      - checkout
      - restore_cache:
          key: npm-cache-{{ checksum "package.json" }}
      - run:
          name: install
          command: npm install
      - save_cache:
          key: npm-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: test
          command: npm test -- --coverage
      - store_artifacts:
          path: coverage
          prefix: coverage
