// Generated by CoffeeScript 2.2.1
(function() {
  var ENDPOINT;

  ENDPOINT = 'ttarrivals.aspx';

  module.exports = function(client) {
    return {
      arrivals: {
        byStop: function(stopId, options = {}, callback) {
          options.stpid = stopId;
          return client.fetch(ENDPOINT, options, callback);
        },
        byStation: function(stationId, options = {}, callback) {
          options.mapid = stationId;
          return client.fetch(ENDPOINT, options, callback);
        }
      }
    };
  };

}).call(this);
