// Generated by CoffeeScript 1.8.0
(function() {
  var ENDPOINT;

  ENDPOINT = 'ttarrivals.aspx';

  module.exports = function(client) {
    return {
      arrivals: {
        byStop: function(stopId, options, callback) {
          if (options == null) {
            options = {};
          }
          options.stpid = stopId;
          return client.fetch(ENDPOINT, options, callback);
        },
        byStation: function(stationId, options, callback) {
          if (options == null) {
            options = {};
          }
          options.mapid = stationId;
          return client.fetch(ENDPOINT, options, callback);
        }
      }
    };
  };

}).call(this);
