// Generated by CoffeeScript 2.2.1
(function() {
  var ENDPOINT;

  ENDPOINT = 'ttfollow.aspx';

  module.exports = function(client) {
    return {
      follow: {
        train: function(runId, callback) {
          return client.fetch(ENDPOINT, {
            runnumber: runId
          }, callback);
        }
      }
    };
  };

}).call(this);
